import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const timesNewRomanSans = localFont({
  src: "./fonts/times-new-roman.ttf",
  variable: "--font-times-new-roman-sans",
  weight: "100 900"
});
const timesNewRomanMono = localFont({
  src: "./fonts/times-new-roman.ttf",
  variable: "--font-times-new-roman",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={` ${timesNewRomanMono.variable} ${timesNewRomanSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
